python -m train \
        --dataset_name residential \
        --num_input 8 \
        --use_disp \
        --N_samples 64 --N_importance 64 \
        --img_wh 640 320 --noise_std 0 \
        --num_epochs 1000 --batch_size 1024 \
        --optimizer adam --lr 5e-4 \
        --lr_scheduler linear \
        --scene_number 0 \
        --exp_name=scene_00 \
        --logging_dir=exp_logs/snerf/residential \
        --root_dir=../../somsi_data \