python -m test \
        --ngpus=1 \
        --nnodes=1 \
        --with_pixel_input \
        --dataset=med_port \
        --logging_path=exp_logs \
        --dataset_path=somsi_data \
        --num_basis=1 \
        --num_inputs=9 \
        --batch_size=1 \
        --epochs=300 \
        --decay_step 60 --decay_gamma 0.8 \
        --learning_rate=0.001 \
        --near=2.5 --far=1000 \
        --exp_name=feats_3 \
        --height=320 \
        --width=640 \
        --feats_per_layer=24 \
        --ckpt_path=ckpts/medieval_port_320x640/medieval_port_feats_24.ckpt
